services:

  db:
    image: mongo:latest
    restart: always
    container_name: audio-bea-crm
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
    ports:
      - "27017:27017"
    #volumes:
    #  - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro