## Brands
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('ACURA', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('ALFA ROMEO', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('ASTON MARTIN', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('AUDI', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('BAIC', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('BENTLEY', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('BMW', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('BUICK', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('CADILLAC', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('CHEVROLET', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('CHRYSLER', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('DODGE', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('FERRARI', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('FIAT', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('FORD', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('GMC', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('HONDA', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('HYUNDAI', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('INFINITI', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('JAGUAR', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('JAC', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('JEEP', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('KIA', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('MAZDA', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('MERCEDES BENZ', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('MITSUBISHI', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('NISSAN', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('PEUGEOT', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('RAM', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('RENAULT', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('SEAT', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('SUBARU', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('SUZUKI', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('TESLA', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('TOYOTA', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('VOLKSWAGEN', b'1');
INSERT INTO `brands` (`brand_name`, `enabled`) VALUES ('VOLVO', b'1');

## SUBBRANDS
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ILX (TECH, A SPEC)', 1, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('TLX 2.4L 8DCT', 1, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('TLX ADVANCE 3.5L 9AT', 1, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('GIULIA SPORT 2.0L', 2, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('GIULIA TI 2.0L', 2, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('GIULIETA VELOCE 1.8L', 2, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('A1 1.0L y 1.5L', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('A1 2.0L', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('A3 1.4L y 2.0L (TODAS LAS VERSIONES)', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('A4 2.0L', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('A5 2.0L', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('AUDI A6 2.0L S TRONIC FRONT (MILD HYBRID)', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('AUDI A6 2.0L S TRONIC QUATTRO (MILD HYBRID)', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('AUDI A7 2.0L S TRONIC QUATTRO (MILD HYBRID)', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Q2 1.4L', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Q2 2.0L', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Q3 1.4L (TODAS LAS VERSIONES)', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Q5 2.0L', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('S3 2.0L', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('TT COUPE 2.0L 169 kW', 4, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('BJ20 1.5L MAN', 5, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('D20 (TODAS LAS VERSIONES)', 5, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('M50S MT 1.5L', 5, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X25 (TODAS LAS VERSIONES)', 5, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X30 1.5L MAN', 5, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X35 (TODAS LAS VERSIONES)', 5, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('118iA (TODAS LAS VERSIONES)', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('120iA (TODAS LAS VERSIONES)', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('220iA (TODAS LAS VERSIONES)', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('320iA (TODAS LAS VERSIONES)', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('330i Sedán SLP', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('330iA Sedán', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('420iA (TODAS LAS VERSIONES)', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('430iA (TODAS LAS VERSIONES)', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('440iA (TODAS LAS VERSIONES)', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('520IA', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('530iA', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('540iA', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('M240iA (TODAS LAS VERSIONES)', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X1 sDrive18iA DKG', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X1 sDrive20iA DKG', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X2 M35iA', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X2 sDrive18iA DKG', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X2 sDrive20iA DKG', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X3 (TODAS LAS VERSIONES)', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('X4 xDrive30i', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Z4 M40iA', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Z4 sDrive20iA', 7, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ENCORE', 8, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ENCORE GX', 8, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ATS COUPE 2.0L', 9, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CTS 2.0L', 9, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('XT4 (TODAS LAS VERSIONES)', 9, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('AVEO (TODAS LAS VERSIONES)', 10, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CAVALIER (TODAS LAS VERSIONES)', 10, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CRUZE (TODAS LAS VERSIONES)', 10, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('EQUINOX (TODAS LAS VERSIONES)', 10, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('MALIBU 1.5L (TODAS SUS VERSIONES)', 10, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('MALIBU 2.0L', 10, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ONIX (TODAS LAS VERSIONES)', 10, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('SPARK (TODAS LAS VERSIONES)', 10, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('TORNADO', 10, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ATTITUDE 1.2L SE CVT', 12, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ATTITUDE 1.2L SXT CVT', 12, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('NEON 1.4L SE', 12, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('NEON 1.6L GT', 12, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('NEON 1.6L SPORT', 12, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('NEON 1.6L SXT', 12, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('500 ABARTH 1.4l MAN', 14, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('MOBI 1.0L LIKE', 14, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('MOBI 1.0L WAY', 14, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('PALIO ADVENTURE 1.6L DUALOGIC', 14, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('PALIO ADVENTURE 1.6L MANUAL', 14, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('UNO 1.3L DRIVE', 14, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('UNO 1.3L SPORTING', 14, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('UNO 1.3L WAY', 14, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ECOSPORT 1.5L MT', 15, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ECOSPORT 2.0L AT', 15, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('EDGE 2.0L', 15, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ESCAPE 2.0L Y 2.5L', 15, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Explorer 2.3L', 15, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Fiesta ST 1.6L Turbo', 15, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('FUSION 2.0L', 15, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('FUSION 2.5L', 15, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('MUSTANG 2.3L', 15, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('TERRAIN (TODAS LAS VERSIONES)', 16, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('GMLX40 1.6L (TODAS LAS VERSIONES)', 16, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ACCORD SEDAN 1.5L (EX Turbo, Sport Plus Turbo)', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ACCORD Touring 2.0L 10AT', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('BR-V (Uniq, Prime)', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CITY (TODAS LAS VERSIONES)', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CIVIC COUPE (TODAS LAS VERSIONES)', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CIVIC i STYLE 2.0L CVT', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CIVIC SEDAN (TODAS LAS VERSIONES)', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CIVIC TYPE R 2.0 MT', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CRV (TODAS LAS VERSIONES)', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('FIT (TODAS LAS VERSIONES)', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('HR-V (TODAS LAS VERSIONES)', 17, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ACCENT 1.6L HB AUT', 18, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('CRETA 1.6L MAN', 18, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('ELANTRA 2.0L (TODAS LAS VERSIONES)', 18, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Grand i10 1.25L AUT (TODAS LAS VERSIONES)', 18, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('Tucson 2.0L Y 2.4L', 18, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('QX30', 19, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('QX50 2WD (TODAS LAS VERSIONES)', 19, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('F TYPE', 20, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('COMPASS 2.4L 4X2 LATITUDE', 22, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('COMPASS 2.4L 4X2 LIMITED', 22, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('COMPASS 2.4L 4X2 LIMITED PREMIUM', 22, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('RENEGADE LATITUDE 1.7L', 22, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('RENEGADE LIMITED 1.7L', 22, b'1');
INSERT INTO `sub_brands` (`sub_brand_name`, `brand_id`, `enabled`) VALUES ('RENEGADE SPORT 1.7L', 22, b'1');

## USERS
insert into users (`enabled`, `password`, `username`) values (true, "fhjkfldsafirehfdsalkfdsah", "andresg");
insert into users (`enabled`, `password`, `username`) values (true, "fhjkfldsafirehfdsalkfdsah", "andresg1006");
insert into users (`enabled`, `password`, `username`) values (true, "fhjkfldsafirehfdsalkfdsah", "pandres");
insert into users (`enabled`, `password`, `username`) values (true, "fhjkfldsafirehfdsalkfdsah", "pandres1006");

## AUTHORITIES
insert into authorities (`authority`, `user_id`) values ("ADMIN",1);
insert into authorities (`authority`, `user_id`) values ("USER",1);
insert into authorities (`authority`, `user_id`) values ("ADMIN",2);
insert into authorities (`authority`, `user_id`) values ("USER",3);
insert into authorities (`authority`, `user_id`) values ("ADMIN",4);


